MyRecipes/Web/MyRecipes.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Common;
    using MyRecipes.Web.Controllers;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

MyRecipes/Web/MyRecipes.Web/Areas/Administration/Controllers/DashboardController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Administration.Dashboard;

    public class DashboardController : AdministrationController
    {
        private readonly ISettingsService settingsService;

        public DashboardController(ISettingsService settingsService)
        {
            this.settingsService = settingsService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel { SettingsCount = this.settingsService.GetCount(), };
            return this.View(viewModel);
        }
    }
}

MyRecipes/Web/MyRecipes.Web/Controllers/BaseController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

MyRecipes/Web/MyRecipes.Web/Controllers/HomeController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data;
    using MyRecipes.Data.Common.Repositories;
    using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService countsService;

        public HomeController(IGetCountsService countsService)
        {
            this.countsService = countsService;
        }

        public IActionResult Index()
        {
            var viewModel = this.countsService.GetCounts();
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

MyRecipes/Web/MyRecipes.Web/Controllers/RecipeApiController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data;
    using MyRecipes.Data.Models;

    [Route("api/[controller]")]
    [ApiController]
    public class RecipeApiController : BaseController
    {
        private readonly ApplicationDbContext db;

        public RecipeApiController(ApplicationDbContext db)
        {
            this.db = db;
        }

        [HttpGet]
        public IEnumerable<Recipe> GetAll()
        {
            return this.db.Recipes.ToList();
        }

        [HttpDelete]
        public ActionResult<string> TestDelete()
        {
            return "Deleted!";
        }

        // if we have id:
        // [HttpPost("{id}")] - from QueryString
        // /api/recipeApi/{id}
        [HttpPost]
        public string TestPost()
        {
            return "Posted";
        }
    }
}

MyRecipes/Web/MyRecipes.Web/Controllers/RecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Recipes;

    public class RecipesController : Controller
    {
        private readonly ICategoriesService categorieService;
        private readonly IRecipesService recipesService;

        public RecipesController(
            ICategoriesService categorieService,
            IRecipesService recipesService)
        {
            this.categorieService = categorieService;
            this.recipesService = recipesService;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel
            {
                CategoriesItems = this.categorieService.GetAllKeyValuePairs(),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var viewModel = new CreateRecipeInputModel
                {
                    CategoriesItems = this.categorieService.GetAllKeyValuePairs(),
                };
                return this.View(viewModel);
            }

            await this.recipesService.AddRecipeAsync(input);

            // Redirect to recipe
            return this.Redirect("/");
        }
    }
}

MyRecipes/Web/MyRecipes.Web/Controllers/SettingsController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data.Common.Repositories;
    using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Settings;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

MyRecipes/Web/MyRecipes.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model MyRecipes.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>
Settings: @this.Model.SettingsCount

MyRecipes/Web/MyRecipes.Web/Views/Home/Index.cshtml
@using MyRecipes.Common
@model MyRecipes.Web.ViewModels.Home.IndexViewModel; 
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
    <div class="col-md-6 offset-md-3">
        <p> We have:</p>
        <ul class="list-group">
            <li class="list-group-item bg-info "> Recipes: @Model.RecipesCount</li>
            <li class="list-group-item bg-light"> Categories: @Model.CategoryCount</li>
            <li class="list-group-item bg-info"> Images: @Model.ImagesCount</li>
            <li class="list-group-item bg-light"> Ingradients: @Model.IngredientsCount</li>
        </ul>
    </div>
</div>

MyRecipes/Web/MyRecipes.Web/Views/Recipes/Create.cshtml
@model MyRecipes.Web.ViewModels.Recipes.CreateRecipeInputModel
@{
    this.ViewData["Title"] = "Добави нова рецепта";
    var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}
<h1>@this.ViewData["Title"]</h1>

<form method="post" class="col-md-9">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Instructions"></label>
        <textarea asp-for="Instructions" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Instructions" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PreparationTime"></label>
        <input asp-for="PreparationTime" class="form-control" rows="5" />
        <span asp-validation-for="PreparationTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CookingTime"></label>
        <input asp-for="CookingTime" class="form-control" rows="5" />
        <span asp-validation-for="CookingTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PortionsCount"></label>
        <input asp-for="PortionsCount" class="form-control" rows="5" />
        <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div id="IngrеdientsContainer">
        <label asp-for="Ingredients"></label>
        <a class="btn btn-success" onclick="AddMoreIngradients()">+</a>
    </div>
    <input type="submit" class="button btn-primary" value="Изпрати" />
</form>
@section Scripts{
    <script>
        var ingredientIndex = 0;
        function AddMoreIngradients() {
            $("#IngrеdientsContainer").append("<div class='form - control'> Съставка: <input type='text' name='Ingredients[" + ingredientIndex + "].IngredientName'  />Количество: <input type='text' name='Ingredients[" + ingredientIndex +"].Quantity'/></div>");
            ingredientIndex++;
        }
    </script>
 }

MyRecipes/Web/MyRecipes.Web/Views/Settings/Index.cshtml
@model MyRecipes.Web.ViewModels.Settings.SettingsListViewModel

@{
    this.ViewData["Title"] = "Settings";
}

<h1>@this.ViewData["Title"]</h1>

@foreach (var setting in this.Model.Settings)
{
    <div>@setting.Id: @setting.NameAndValue</div>
}

<a asp-action="InsertSetting" class="btn btn-primary">Insert new</a>

MyRecipes/Web/MyRecipes.Web/Views/Shared/_Layout.cshtml
@using MyRecipes.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create Recipe</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>